
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


mqtt:
  sensor:
      #sensor1
      - name: "Temperature"
        state_topic: "plant1/hum_temp_sensor/temperature"
        unit_of_measurement: "°C"
      - name: "Humidity"
        state_topic: "plant1/hum_temp_sensor/humidity"
        unit_of_measurement: "%"
      - name: "Dew Point"
        state_topic: "plant1/hum_temp_sensor/dewpoint"
        unit_of_measurement: "°C"
      #sensor2
      - name: "IR Irradianace"
        state_topic: "plant1/light_sensor/ir_irradiance"
        unit_of_measurement: "W/m2"
      - name: "UV Index"
        state_topic: "plant1/light_sensor/uv_index"
        unit_of_measurement: ""
      - name: "Visible Light"
        state_topic: "plant1/light_sensor/lux"
        unit_of_measurement: "lx"




influxdb:
  host: !env_var VICTORIAMETRICS_HOST
  port: !env_var VICTORIAMETRICS_PORT
  ssl: false
  verify_ssl: false
  max_retries: 3
  default_measurement: sta